### PR TITLE
Automatic installation of Pydesigner and all dependencies

### PR DESCRIPTION
**Pull request by TheJaeger**
This PR adds the files `setup.py`, `designer/info.py`, `MANIFEST.in` to manage auto installation and updates.

* `setup.py`: configures distribution of Pydesigner; pulls info from `info.py`
* `MANIFEST.in`: controls non-coding files to include into distribution
* `info.py`: contains information on PyDesigner

Users can install PyDesigner into their environment using command line. Simply `cd` into the PyDesigner repo directory then execute `pip install .` to install the package as `pydesigner`. Users can then simply execute the CLI with `pydesigner [options] dwi`

Developers can install the code in editable mode via `pip install -e .` within their repo so changes made from new pulls will be reflected in the executable.

### CODE REVIEW

**Comment by jbteves** [comment]
Key issue: you want to `pip install -e .` if your codebase will change. Only end-users should use `pip install .`.

**Comment by TheJaeger** [comment]
Right. Instructions above are for end-users. Let me add that clarification.

**Comment by jbteves** [comment]
It turns out that this isn't working on a clean conda environment. For some reason pip install isn't adding numpy correctly. Try a clean conda environment on your end and see if you can replicate.

**Comment by TheJaeger** [comment]
It's working on my end on a freshly created environment with the command `conda create -n test python=3.7`. See screenshot for log.

Screen Shot 2020-01-22 at 10 37 02 AM

**Comment by TheJaeger** [comment]
PIE-TON! LOL!

**Comment by jbteves** [comment]
What do you mean, PIE-TON?

**Comment by TheJaeger** [comment]
Look at my branch's spelling.

**Comment by TheJaeger** [comment]
New commits fix most issues we were having. I'm not sure about the Numpy error, but the application packages correctly now.

**Comment by jbteves** [comment]
It turns out there's an issue with pip-intalling numpy, you have to use a conda install. For some reason now it can't find nibabel, I assume because that's pip-installed as well.

**Comment by TheJaeger** [comment]
As of last commit, this branch has been verified to be stable on Mac and Ubuntu within Docker. Both systems produce a consistently executing `setup.py` to install PyDesigner. Users can simply call pydesigner from the CLI via the command `pydesigner [options] dwi` after setup.

Users who do not want to install the script have to execute it from the root directory with the command `python3 designer/pydesigner.py [options] dwi`. The script can no longer be executed from within `PyDesigner/designer` directory. This behavior was changed to accommodate the presence of submodules within the primary designer folder.

There is also a new **Dockerfile** within the root directory for building a Docker image locally. Running `docker build -t pydesigner path_to_repo` will build a new Docker image titled 'pydesigner' contents of the root directory.

**Comment by TheJaeger** [comment]
Close #15

**Pull request merged**
